version: '3.8'

services:
  om1:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1:latest
    container_name: om1
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - CYCLONEDDS_HOME=/app/cyclonedds/install
      - CYCLONEDDS_URI=file:///cyclonedds/cyclonedds.xml
      - CMAKE_PREFIX_PATH=/app/cyclonedds/install
      - OM_API_KEY=${OM_API_KEY}
      - VIRTUAL_ENV=/app/OM1/.venv
      - PATH=/app/OM1/.venv/bin:$PATH
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - ALSA_CARD=0
    volumes:
      - ./.venv:/app/OM1/.venv
      - ./cyclonedx:/cyclonedx
      - /dev/snd:/dev/snd:rw
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:rw
      - /usr/share/alsa:/usr/share/alsa:ro
      - /etc/asound.conf:/etc/asound.conf:ro
    devices:
      - /dev/snd:/dev/snd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    group_add:
      - audio
    command: ["spot"]
